export const countryCodes = [
    { code: "+57", name: "Colombia", flag: "🇨🇴" },
    { code: "+1", name: "USA/Canada", flag: "🇺🇸/🇨🇦" },
    { code: "+52", name: "Mexico", flag: "🇲🇽" },
    { code: "+34", name: "Spain", flag: "🇪🇸" },
    { code: "+54", name: "Argentina", flag: "🇦🇷" },
    { code: "+56", name: "Chile", flag: "🇨🇱" },
    { code: "+51", name: "Peru", flag: "🇵🇪" },
    { code: "+593", name: "Ecuador", flag: "🇪🇨" },
    { code: "+507", name: "Panama", flag: "🇵🇦" },
    { code: "+506", name: "Costa Rica", flag: "🇨🇷" },
    { code: "+598", name: "Uruguay", flag: "🇺🇾" },
    { code: "+58", name: "Venezuela", flag: "🇻🇪" },
    { code: "+591", name: "Bolivia", flag: "🇧🇴" },
    { code: "+595", name: "Paraguay", flag: "🇵🇾" },
    { code: "+503", name: "El Salvador", flag: "🇸🇻" },
    { code: "+504", name: "Honduras", flag: "🇭🇳" },
    { code: "+502", name: "Guatemala", flag: "🇬🇹" },
    { code: "+505", name: "Nicaragua", flag: "🇳🇮" },
    { code: "+1-809", name: "Dominican Rep.", flag: "🇩🇴" },
    { code: "+53", name: "Cuba", flag: "🇨🇺" },
];
